# html/util library for prep
# contains my favourite shortcuts for html statements
#
# -lynx
#
#space [num] generates num empty lines with <pre>..</pre>
#
#fullscreen_on and
#fullscreen_off	toggle table commands to fill the whole browser display
#	exactly with the table contents. uses "th" for efficiency.
#

sub do_space {
	local($x) = @_;
	print '<pre>', "\n" x $x, "</pre>\n";
}

sub do_fullscreen_on { print <<X; }
<table height="100%" width="100%"><tr><th>
X

sub do_fullscreen_off { print <<X; }
</th></tr></table>
X

sub do_sign { print <<X; }
<!-- this file was generated by prep - the hacker's choice in preprocessors -->
X

1;	# yes, larry..
